### ISSUE TITLE
Validation Table ASHRAE-55 : Incorrect value for Met greater than 1

### ISSUE THREAD

**Issue by julie9** [CenterForTheBuiltEnvironment/comfort_tool#56]
The SET values calculated by the CBE tool do not correspond to the validation values for the last 2 lines of the validation table provided by ASHRAE-55 Table D3 with Met=2.0 and Met=4.0.

ta | tr | vel | rh | met | clo | valid | Calculated by CBE tool
-- | -- | -- | -- | -- | -- | -- | --
25 | 25 | 0.15 | 0.5 | 1 | 0.5 | 23.8 | 23.8  OK
… |   |   |   |   |   |   |  
25 | 25 | 0.15 | 0.5 | 0.8 | 0.5 | 23.3 | 23.3  OK
25 | 25 | 0.15 | 0.5 | 2 | 0.5 | 29.7 | 26.3  X
25 | 25 | 0.15 | 0.5 | 4 | 0.5 | 36.0 | 30.6  X

![CBE0](https://user-images.githubusercontent.com/12814617/97526662-fc567e80-197f-11eb-80fd-fe2f667bc7f5.png)

![CBE1](https://user-images.githubusercontent.com/12814617/97526667-feb8d880-197f-11eb-8dac-deba2fbfe211.png)

**Comment by FedericoTartarini** [comment]
@julie9 please note that The CBE comfort tool automatically calculates the [relative air speed](http://centerforthebuiltenvironment.github.io/comfort_tool/docs/pmv#relative-air-speed) and the [dynamic clothing insulation](http://centerforthebuiltenvironment.github.io/comfort_tool/docs/pmv#dynamic-clothing-insulation).
See links for more information, hence that it should be the reason why the two values do not match.

You can also use pythermalcomfort to calculate the SET temperature if you are a Python user https://pythermalcomfort.readthedocs.io/en/latest/_modules/pythermalcomfort/models.html#set_tmp

**Comment by FedericoTartarini** [comment]
@julie9 I have written a test to validate the SET function commit 006cd213ee3dc18d2b7ba570863ec094f5106089. 

However, as you can see in commit 27c8a969631dd9da37f201a6f5d7c8e26cc1a188 we have now changed how the `h_c -- convective heat transfer coefficient` is calculated since there was an error in the original code. Consequently, for high values of met (met > 1) the value obtained with the CBE comfort tool will not match the reference table, however, the correct one is the one from our tool.

**Comment by julie9** [comment]
Hi @FedericoTartarini, thank you very much for taking the time to look into this. This is interesting. I am in rush this week but I'll look into this further as soon as I can.

**Comment by FedericoTartarini** [comment]
@julie9 please let me know if you have any questions.
