### ISSUE TITLE
Clothing Selections are Incomplete Given the List of Activities

### ISSUE THREAD

**Issue by jbasen** [CenterForTheBuiltEnvironment/comfort_tool#71]
First, thanks for providing this great tool

I really can't say if this is a bug or a feature request.  The issue is that you include sleeping as an activity with a metabolic rate of .7.  However, there aren't any clothing selections that would correspond to light blanket, heavy blanket, comforter, sheet, etc. that would relate to what a person would be insulated with at night while sleeping.  

In a residential setting when trying to look at what air temperature would provide comfort at night these "clothing" options are critical.  

Can these options be added to the drop-down for the calculator?  Alternatively could you just include a link to a larger list of possible clothing values so the proper clo value can be entered.

Thanks

**Comment by FedericoTartarini** [comment]
Hi, thank you for pointing this out. We included a met of 0.7 since it is the met for a resting person. However, the ASHRAE 55 standard does not apply to people who are sleeling. Consequently, we did not include clothing or bedding that a person would use when sleeping since the model has never been tested or validated for that scenario. Please refrain from using the PMV model to estimate comfort conditions for people who are sleeping.

**Comment by jbasen** [comment]
Thanks Federico.  

Is there an alternate comfort model that could be used for people who are sleeping?

Thanks again.

**Comment by FedericoTartarini** [comment]
You are welcome. I am unaware of a model that can be used for sleeping people. I guess you could use the two-nodes model or PMV model as a guide and as a starting point but their results may not be accurate.

**Comment by jbasen** [comment]
Thanks again. I'll take a look at the 2-node model.
