### ISSUE TITLE
Adaptive comfort Elevated air movement table wronglu applied to EN15251

### ISSUE THREAD

**Issue by stefanoschiavon** [CenterForTheBuiltEnvironment/comfort_tool#9]
The ASHRAE adaptive thermal comfort model has an adjustment if elevated air movement is present. This feature is not present in the EN15251 standard. There is an error in the EN15251 adaptive comfort in the tool because there is the elevated air speed adjustment
![image009](https://user-images.githubusercontent.com/8670167/51444172-03c7fe80-1ca9-11e9-9585-eaac1ce6a1a7.png)
.

**Comment by FedericoTartarini** [comment]
Fixed. Waiting for Tyler to accept Pull request.

**Comment by chriswmackey** [comment]
@stefanoschiavon ,

Out of curiosity, where did the original elevated air speed model that was implemented here for EN-15251 come from?  Was it a part of the European standard and they recently removed it?  Or did we see it in a research paper and mistakenly thought it was in EN-15251?

I have to admit that I liked this elevated air speed model that is being removed since it had a continuous relationship between air speed and cooling effect (unlike the ASHRAE-55 one that is more of a step function at specific air speeds).  The continuous relationship intuitively feels more correct even though, as this issue suggests, the values given by the model might not be accurate.
